# Generated by Django 5.0.4 on 2024-05-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwoPreviewPicks',
            new_name='TwoPreviewPick',
        ),
    ]
