# Generated by Django 5.0.4 on 2024-05-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0002_rename_twopreviewpicks_twopreviewpick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='schedules',
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movienook.movie'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movienook.theater'),
        ),
    ]
