# Generated by Django 5.0.4 on 2024-05-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0003_remove_theater_schedules_showtime_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='timeslot_1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='timeslot_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='timeslot_3',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='timeslot_4',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movienook.movie'),
        ),
    ]
