# Generated by Django 5.0.4 on 2024-05-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0004_remove_showtime_end_time_remove_showtime_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='id',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movienook.movie', unique=True),
        ),
    ]
