# Generated by Django 5.0.4 on 2024-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0005_remove_showtime_id_alter_showtime_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='timeslot_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='timeslot_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='timeslot_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='timeslot_4',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
