# Generated by Django 5.0.4 on 2024-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0006_alter_showtime_timeslot_1_alter_showtime_timeslot_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='date_4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
