# Generated by Django 5.0.4 on 2024-05-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0007_theater_date_1_theater_date_2_theater_date_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showing_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movienook.movie'),
        ),
    ]
