# Generated by Django 5.0.4 on 2024-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0010_alter_movie_showing_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='movietransaction',
            name='showtime',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
