# Generated by Django 5.0.4 on 2024-05-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0011_alter_movie_options_movietransaction_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietransaction',
            name='showtime',
        ),
    ]
