# Generated by Django 5.0.4 on 2024-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('gcash', 'GCash')], max_length=50),
        ),
    ]
