# Generated by Django 5.0.4 on 2024-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0015_payment_contact_payment_email_alter_movie_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AddField(
            model_name='movietransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
