# Generated by Django 5.0.4 on 2024-05-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienook', '0017_theaterreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='reservation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
